language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
sudo: required
install: make build
script: make test
after_success:
  - make sdist

deploy:
    # test pypi
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "Dan.Riti"
    password:
    on:
      branch: master
      tags: false
deploy:
  provider: pypi
  user: "ons.digital"
  password:
    secure: "TODO"
  on:
    tags: true